config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  resources :students do
    resources :courses, only: :index
    post :add, on: :collection
  end
  resources :courses do
    resources :students, only: :index
    post :attend, on: :member
    post :exit, on: :member
  end
  resources :categories, except: :destroy do
    resources :courses, only: :index
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'courses#index'
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  MAX_ACTUAL_COURSES = 2
  ADMIN_EMAIL = "emanolova@gmail.com"

  has_and_belongs_to_many :courses

  has_attached_file :picture,
                    styles: { medium: "300x300#", thumb: "100x100#" },
                    default_url: ":style/missing.png"

  validates_attachment :picture,
                       content_type: { content_type: "image/jpeg" },
                       size: { in: 0..2.megabytes }

  validates :first_name, presence: true, length: { in: 3..15 }
  validates :last_name, presence: true, length: { in: 3..15 }

  def attend!(course)
    raise Error::CourseFullError.new if course.complete?
    raise Error::TooManyCoursesAtATimeError.new if actual_courses.size >= MAX_ACTUAL_COURSES
    raise Error::NotEligibleForCourseError.new if course.level - 1 > (max_level_for_category(course.category)||0)

    courses << course

    if actual_courses.size >= MAX_ACTUAL_COURSES
      courses.delete(courses.all - actual_courses)
    end
  end

  def admin?
    email == ADMIN_EMAIL
  end

  private
  def actual_courses
    courses.all.select do |course|
      course.actual?
    end
  end

  def max_level_for_category(category)
    courses_in_the_same_category = courses.where(category_id: category.id)
    courses_in_the_same_category.maximum(:level)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:add, :new, :index, :destroy]
  before_action :authenticate_owner!, only: [:edit, :update]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @all_courses = Course.all
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students/add
  # POST /students/add.json
  def add
    @student = Student.new(student_params)
    @student.password = Devise.friendly_token.first(8)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :picture, :email)
    end

    def authenticate_owner!
      insufficient_privileges! unless current_student == @student || current_student.admin?
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_courses.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Level</th>
    <th>Category</th>
    <th>Confirmed</th>
    <th>Actions</th>
  </tr>
  <% courses.each do |course| %>
    <tr>
      <td><%= course.name %></td>
      <td><%= course.level %></td>
      <td><%= course.category.name %></td>
      <td><%= course.actual? %></td>
      <td>
        <%= link_to course, class: 'btn', title: 'View course' do %>
          <i class="fa fa-eye"></i>
        <% end %>

        <% if student.courses.include?(course) %>
          <%= link_to exit_course_path(course, student_id: student.id), method: :post, data: { confirm: 'Are you sure?' }, class: 'btn', title: 'Exit course' do %>
            <i class="fa fa-sign-out"></i></a>
          <% end %>
        <% else %>
          <%= link_to attend_course_path(course, student_id: student.id), method: :post, class: 'btn', title: 'Enroll in course' do %>
            <i class="fa fa-sign-in"></i></a>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/students/_form_fields.html.erb
<% if student.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

    <ul>
    <% student.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :picture %>
  <%= form.file_field :picture %>
</div>

<div class="field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name, id: :student_first_name %>
</div>

<div class="field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name, id: :student_last_name %>
</div>

<div class="field">
  <%= form.label :email %>
  <%= form.email_field :email %>
</div>

<div class="actions">
  <%= form.submit class: 'btn btn-primary btn-sm' %>
</div>

app/views/students/edit.html.erb
<h2>Editing Student</h2>

<%= form_with(model: @student, local: true) do |form| %>
  <%= render 'form_fields', student: @student, form: form %>
<% end %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Students</h2>

<table>
  <thead>
    <tr>
      <th></th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= image_tag student.picture.url(:thumb) %>
        </td>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.email %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path, class: 'btn btn-secondary btn-sm' %>

app/views/students/new.html.erb
<h2>New Student</h2>

<%= form_with(model: @student, local: true, url: add_students_path, method: :post) do |form| %>
  <%= render 'form_fields', student: @student, form: form %>
<% end %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<article class="d-flex align-items-center">
  <%= image_tag @student.picture.url(:medium), class: "my-3 mr-4" %>
  <div>
    <h4><%= @student.first_name %> <%= @student.last_name %></h4>

    <p>
      <strong>Email:</strong>
      <%= @student.email %>
    </p>

    <p>
      <strong>Last login time:</strong>
      <%= @student.last_sign_in_at ? l(@student.last_sign_in_at, { format: :long }) : 'never' %>
    </p>

  </div>
</article>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>


<div class="card card-outline-primary mt-3">
  <h4 class="card-header card-inverse card-primary">Enrolled Courses</h4>
  <div class="card-block">
    <%= render 'courses', student: @student, courses: @student.courses %>
  </div>
</div>

<div class="card card-outline-primary mt-3">
  <h4 class="card-header card-inverse card-info">All Courses</h4>
  <div class="card-block">
    <%= render 'courses', student: @student, courses: @all_courses - @student.courses %>
  </div>
</div>