config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  resources :students do
    resources :courses, only: :index
    post :add, on: :collection
  end
  resources :courses do
    resources :students, only: :index
    post :attend, on: :member
    post :exit, on: :member
  end
  resources :categories, except: :destroy do
    resources :courses, only: :index
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'courses#index'
end

app/views/layouts/_header.html.erb
<header class="header my-4 d-flex align-items-center justify-content-between">
  <h1 class="text-muted">Academy App</h1>

  <ul class="nav nav-pills">
    <li class="nav-item">
      <% if student_signed_in? %>
        <%= link_to 'Profile', current_student %>
        |
        <%= link_to 'Log out', destroy_student_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Log in', new_student_session_path %>
        |
        <%= link_to 'Sign up', new_student_registration_path %>
      <% end %>
    </li>
  </ul>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AcademyApp</title>
    <%= csrf_meta_tags %>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>

      <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-#{name == 'notice' ? 'info' : 'danger'}") %>
      <% end %>

      <nav>
        <ul class="nav nav-tabs">
          <% %w(courses students categories).each do |controller| %>
          <li class="nav-item">
            <%= link_to controller.capitalize, "/#{controller}/", class: "nav-link #{'active' if controller_name == controller}" %>
          </li>
          <% end %>
        </ul>
      </nav>

      <main role="main" class="tab-content">
        <%= yield %>
      </main>

      <footer class="footer">
        <p>© Company 2017</p>
      </footer>

    </div>
  </body>
</html>